-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-04-15 13:51:00 CEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012

CREATE DATABASE Sklep_Temp
GO

USE Sklep_Temp
GO

CREATE TABLE Adres 
    (
     id_adres INTEGER NOT NULL , 
     miasto NVARCHAR(50) NOT NULL , 
     ulica NVARCHAR(50) NOT NULL , 
     nr_budynku VARCHAR(5) NOT NULL , 
     nr_mieszkania VARCHAR(5) , 
     kod_pocztowy CHAR (6) NOT NULL 
    )
GO

ALTER TABLE Adres ADD CONSTRAINT Adres_PK PRIMARY KEY CLUSTERED (id_adres)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Kategoria 
    (
     id_kategoria INTEGER NOT NULL , 
     nazwa NVARCHAR (25) NOT NULL , 
     Kategoria_id_kategoria INTEGER 
    )
GO

ALTER TABLE Kategoria ADD CONSTRAINT Kategoria_PK PRIMARY KEY CLUSTERED (id_kategoria)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Klient 
    (
     id_klient INTEGER NOT NULL , 
     Osoba_id_osoba INTEGER NOT NULL , 
     regon CHAR (9) 
    )
GO 

CREATE UNIQUE NONCLUSTERED INDEX 
    Klient__IDX ON Klient 
    ( 
     Osoba_id_osoba 
    ) 
GO

ALTER TABLE Klient ADD CONSTRAINT Klient_PK PRIMARY KEY CLUSTERED (id_klient)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Osoba 
    (
     id_osoba INTEGER NOT NULL , 
     pesel CHAR (11) NOT NULL , 
     imie NVARCHAR (25) NOT NULL , 
     nazwisko NVARCHAR (25) NOT NULL , 
     Adres_id_adres INTEGER NOT NULL , 
     nr_telefonu CHAR (9) NOT NULL , 
     email VARCHAR (50) NOT NULL 
    )
GO

ALTER TABLE Osoba ADD CONSTRAINT Osoba_PK PRIMARY KEY CLUSTERED (id_osoba)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Pracownik 
    (
     Osoba_id_osoba INTEGER NOT NULL , 
     stanowisko NVARCHAR (25) NOT NULL , 
     data_poczatek_pracy DATE NOT NULL , 
     data_koniec_pracy DATE , 
     pensja FLOAT , 
     id_pracownik INTEGER NOT NULL 
    )
GO 

-- Dodaj indeks klastrujący na kolumnie data_poczatek_pracy
CREATE CLUSTERED INDEX Pracownik_DataPoczatekPracy_IDX ON Pracownik (data_poczatek_pracy);
GO

ALTER TABLE Pracownik ADD CONSTRAINT Pracownik_PK PRIMARY KEY NONCLUSTERED (id_pracownik)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Produkt 
    (
     id_produkt INTEGER NOT NULL , 
     nazwa NVARCHAR (50) NOT NULL , 
     Kategoria_id_kategoria INTEGER NOT NULL , 
     opis NVARCHAR (200) NOT NULL , 
     cena FLOAT NOT NULL , 
     ilosc INTEGER NOT NULL 
    )
GO

ALTER TABLE Produkt ADD CONSTRAINT Produkt_PK PRIMARY KEY CLUSTERED (id_produkt)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE ProduktZamowienie 
    (
     Produkt_id_produkt INTEGER NOT NULL , 
     Zamowienie_id_zamowienie INTEGER NOT NULL , 
     ilosc INTEGER NOT NULL , 
     rabat INTEGER , 
     cena_produktow INTEGER 
    )
GO

ALTER TABLE ProduktZamowienie ADD CONSTRAINT ProduktZamowienie_PK PRIMARY KEY CLUSTERED (Produkt_id_produkt, Zamowienie_id_zamowienie)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Zamowienie 
    (
     id_zamowienie INTEGER NOT NULL , 
     data_zamowienie DATETIME , 
     Pracownik_Osoba_id_osoba INTEGER NOT NULL , 
     Klient_id_klient INTEGER NOT NULL , 
     czy_oplacone BIT NOT NULL , 
     czy_wyslane BIT NOT NULL , 
     cena_laczna FLOAT NOT NULL , 
     id_pracownik1 INTEGER NOT NULL 
    )
GO

-- Dodaj indeks klastrujący na kolumnie data_zamowienie
CREATE CLUSTERED INDEX Zamowienie_DataZamowienie_IDX ON Zamowienie (data_zamowienie);
GO

ALTER TABLE Zamowienie ADD CONSTRAINT Zamowienie_PK PRIMARY KEY NONCLUSTERED (id_zamowienie)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO


ALTER TABLE Kategoria 
    ADD CONSTRAINT Kategoria_Kategoria_FK FOREIGN KEY 
    ( 
     Kategoria_id_kategoria
    ) 
    REFERENCES Kategoria 
    ( 
     id_kategoria 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Klient 
    ADD CONSTRAINT Klient_Osoba_FK FOREIGN KEY 
    ( 
     Osoba_id_osoba
    ) 
    REFERENCES Osoba 
    ( 
     id_osoba 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Osoba 
    ADD CONSTRAINT Osoba_Adres_FK FOREIGN KEY 
    ( 
     Adres_id_adres
    ) 
    REFERENCES Adres 
    ( 
     id_adres 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Pracownik 
    ADD CONSTRAINT Pracownik_Osoba_FK FOREIGN KEY 
    ( 
     Osoba_id_osoba
    ) 
    REFERENCES Osoba 
    ( 
     id_osoba 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Produkt 
    ADD CONSTRAINT Produkt_Kategoria_FK FOREIGN KEY 
    ( 
     Kategoria_id_kategoria
    ) 
    REFERENCES Kategoria 
    ( 
     id_kategoria 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ProduktZamowienie 
    ADD CONSTRAINT ProduktZamowienie_Produkt_FK FOREIGN KEY 
    ( 
     Produkt_id_produkt
    ) 
    REFERENCES Produkt 
    ( 
     id_produkt 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ProduktZamowienie 
    ADD CONSTRAINT ProduktZamowienie_Zamowienie_FK FOREIGN KEY 
    ( 
     Zamowienie_id_zamowienie
    ) 
    REFERENCES Zamowienie 
    ( 
     id_zamowienie 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Zamowienie 
    ADD CONSTRAINT Zamowienie_Klient_FK FOREIGN KEY 
    ( 
     Klient_id_klient
    ) 
    REFERENCES Klient 
    ( 
     id_klient 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Zamowienie 
    ADD CONSTRAINT Zamowienie_Pracownik_FK FOREIGN KEY 
    ( 
     id_pracownik1
    ) 
    REFERENCES Pracownik 
    ( 
     id_pracownik 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             4
-- ALTER TABLE                             17
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
